let nomesBrutos = ["Telha Americana vermelha Resinada 12/m²",
  "Telha Americana Mesclada",
  "Telha de Concreto Cinza 10,4/M²",
  "Telha de Fibrocimento Ondulada 5mm",
  "Telha de Fibrocimento Ondulada 6mm",
  "Telha de Fibrocimento Vogatex 4mm ",
  "Telha Portuguesa Vermelha Resinada 15/m²",
  "Telha Portuguesa de Vidro",
  "Telha Romana de Vidro",
  "Telha Romana Vermelha Resinada 15/m²",
  "Manta Termica dupla face 10m²",
  "Caibro de Madeira Cambará 5x5cm",
  "Viga de Madeira Cambará 5x15cm",
  "Prancha de Madeira Cambará 5x20cm",
  "Prancha de Madeira Cambará 5x25cm",
  "Prancha de Madeira Cambará 5x30cm",
  "Ripa de Madeira Cambará 1,5 x 5cm",
  "Ripa de Madeira Peroba 1,8 x 5cm",
  "Ripão de Madeira Peroba 2,3x5cm",
  "Caibro de Madeira Peroba 5x5cm",
  "Caibro de Madeira Peroba 5x7cm",
  "Viga de Madeira Peroba 5x11cm",
  "Viga de Madeira Peroba 5x15cm",
  "Tabua de Madeira Pinus",
  "Sarrafo de Madeira Pinus",
  "Chapa de Madeirite Rosa 2,20x1,10m",
  "Tabua de Madeira Mista  2x20cm",
  "Tabua de Madeira Mista 2x25cm",
  "Tabua de Madeira Mista 2x30cm",
  "Sarrafo de Madeira Cedro Mesclado 2x5cm",
  "Sarrafo de Madeira Cedro Mesclado 2x10cm",
  "Sarrafo de Madeira Cedro Mesclado 2x15cm",
  "Tabua de Madeira Cedro Mesclado 2x20cm",
  "Tabua de Madeira Cedro Mesclado 2x25cm",
  "Tabua de Madeira Cedro Mesclado 2x30cm",
  "Forro de Madeira Cedro Mesclado por m²",
  "Forro de Madeira Cedro Vermelho por m²",
  "Capa Lateral de Concreto Cinza 3/m",
  "Cumeeira de Concreto Grafite 3/m",
  "Capa Lateral de Concreto Grafite 3/m",
  "Telha de Concreto Grafite 10,4/m²",
  "Viga de Madeira Cambará 5x11cm",
  "Caibro de Madeira Cambará 5x7cm",
  "Ripão de Madeira Cambará 2,3x5cm",
  "Madeirite Plastificado Preto 2,20 x 1,10m",
  "Prancha de Madeira Peroba 5x20cm",
  "Prancha de Madeira Peroba 5x25cm",
  "Prancha de Madeira Peroba 5x30cm",
  "Meia Cana de Madeira Cedro"]

  let chavesPesquisa = {}

  let valuesString = nomesBrutos.map(nome => `('${nome}', '${nome}', 'nome')`).join(", ");

  console.log(valuesString)
